export default {
  "login": "dayana-sog",
  "id": 57035171,
  "node_id": "MDQ6VXNlcjU3MDM1MTcx",
  "avatar_url": "https://avatars2.githubusercontent.com/u/57035171?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/dayana-sog",
  "html_url": "https://github.com/dayana-sog",
  "followers_url": "https://api.github.com/users/dayana-sog/followers",
  "following_url": "https://api.github.com/users/dayana-sog/following{/other_user}",
  "gists_url": "https://api.github.com/users/dayana-sog/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/dayana-sog/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/dayana-sog/subscriptions",
  "organizations_url": "https://api.github.com/users/dayana-sog/orgs",
  "repos_url": "https://api.github.com/users/dayana-sog/repos",
  "events_url": "https://api.github.com/users/dayana-sog/events{/privacy}",
  "received_events_url": "https://api.github.com/users/dayana-sog/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Dayana Gonçalves",
  "company": null,
  "blog": "dayanasog23@gmail.com",
  "location": "Lisbon, Portugal",
  "email": null,
  "hireable": null,
  "bio": "Full-Stack Developer \r\nReact.js | Node.js | React Native",
  "twitter_username": null,
  "public_repos": 42,
  "public_gists": 0,
  "followers": 61,
  "following": 39,
  "created_at": "2019-10-26T10:51:58Z",
  "updated_at": "2020-12-17T12:02:49Z"
};